iroha:
  toriiAddress: grpc://localhost:32835
  user:
    privateKeyHex:
    publicKeyHex:
    id: data_collector@notary

scheduling:
  iroha:
    block:
      request: 10000


postgres:
  host:     localhost
  port:     5432
  database: data_collector

spring:
  # Spring JDBC configuration
  datasource:
    driverClassName: org.postgresql.Driver
    url:      jdbc:postgresql://${postgres.host}:${postgres.port}/${postgres.database}?useSSL=false
    username: test
    password: test
  h2:
    console:
       enabled: true

  # Spring Data JPA configuration
  jpa:
    hibernate:
      # To be updated in real production usage! Possible values none;update;create
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:liquibase-master.xml

logging:
  level:
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR