iroha:
  host: localhost
  port: 32835
  toriiAddress: grpc://${iroha.host}:${iroha.port}
  user:
    privateKeyHex: 37C2070BD7C628B2ABA61F6C353DF06504A92F6997D8658F3EE69DC598B57CA2
    publicKeyHex: 97B888554684FB30F29FAB92991AB7ECEFFFE433AB3AF501E5DEAEE69392518C
    id: data_collector@notary
  templates:
    transferBilling: transfer_billing@
    custodyBilling: custody_billing@
    accountCreationBilling: account_creation_billing@
    exchangeBilling: exchange_billing@
    withdrawalBilling: withdrawal_billing@

scheduling:
  iroha:
    block:
      request: 10000


postgres:
  host:     localhost
  port:     5432
  database: data_collector

spring:
  # Spring JDBC configuration
  datasource:
    driverClassName: org.postgresql.Driver
    url:      jdbc:postgresql://${postgres.host}:${postgres.port}/${postgres.database}?useSSL=false
    username: test
    password: test
  # Spring Data JPA configuration
  jpa:
    hibernate:
      # To be updated in real production usage! Possible values none;update;create
      ddl-auto: none
    show-sql: true
  liquibase:
    change-log: classpath:liquibase-master.xml
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

server:
  port: 8080

logging:
  level:
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR
