version: '3.5'

services:
  data-collector:
    image: nexus.iroha.tech:19002/d3-deploy/data-collector:develop
    container_name: "data-collector"
    restart: on-failure
    ports:
      - 8087:8080
    depends_on:
      - dc-postgres
      - d3-rmq
    environment:
      POSTGRES_HOST: dc-postgres
      POSTGRES_DATABASE: postgres
      RMQ_HOST: d3-rmq
      IROHA_HOST: d3-iroha
      IROHA_PORT: 50051
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test
    networks:
      - d3-network

  report-service:
    image: nexus.iroha.tech:19002/d3-deploy/report-service:develop
    container_name: "report-service"
    restart: on-failure
    ports:
      - 8090:8090
    depends_on:
      - data-collector
    environment:
      POSTGRES_HOST: dc-postgres
      POSTGRES_DATABASE: postgres
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test
    networks:
      - d3-network

  dc-postgres:
    image: postgres
    container_name: "dc-postgres"
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test
    networks:
      - d3-network

  d3-rmq:
    image: rabbitmq:3-management
    container_name: d3-rmq
    networks:
      - d3-network

networks:
  d3-network:
