version: '3.1'

services:
  data-collector:
    image: nexus.iroha.tech:19002/d3-deploy/data-collector:develop
    container_name: "data-collector"
    restart: on-failure
    ports:
      - 8080:8080
    depends_on:
      - dc-postgres
      - brvs-rmq
    environment:
      POSTGRES_HOST: dc-postgres
      POSTGRES_DATABASE: postgres
      SPRING_RABBITMQ_HOST: brvs-rmq
      IROHA_HOST: d3-iroha
      IROHA_PORT: 50051
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test

  report-service:
    image: nexus.iroha.tech:19002/d3-deploy/report-service:develop
    container_name: "report-service"
    restart: on-failure
    ports:
      - 8090:8090
    depends_on:
      - data-collector
    environment:
      POSTGRES_HOST: dc-postgres
      POSTGRES_DATABASE: postgres
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test

  dc-postgres:
    image: postgres
    container_name: "dc-postgres"
    environment:
      POSTGRES_PASSWORD: test
      POSTGRES_USER: test

  brvs-rmq:
    image: rabbitmq:3-management
    container_name: "brvs-rmq"
