rmq:
  host: d3-rmq
  port: 5672

postgres:
  host:     localhost
  port:     15432
  database: postgres

spring:
  # Spring JDBC configuration
  datasource:
    driverClassName: org.postgresql.Driver
    url:      jdbc:postgresql://${postgres.host}:${postgres.port}/${postgres.database}?useSSL=false
    username: test
    password: test
  # Spring Data JPA configuration
  jpa:
    hibernate:
      # To be updated in real production usage! Possible values none;update;create
      ddl-auto: none
    show-sql: true
  output:
    ansi:
      enabled: NEVER
  liquibase:
    change-log: classpath:liquibase-master.xml

hibernate:
  hbm2ddl:
    auto: update

logging:
  level:
    org.hibernate.engine.jdbc.env.internal.LobCreatorBuilderImpl: ERROR
